service: scale-of-belief-import

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  versionFunctions: false
  memorySize: 256
  environment: ${file(serverless/environment.js)}
  $<<: ${file(serverless/provider.js)}

functions:
  api:
    handler: api/import.handler
    timeout: 300
    events:
      - http:
          path: /api/import
          method: ANY
  campaign:
    handler: campaign/import.handler
    timeout: 300
    events:
      - schedule: cron(0 6 * * ? *)
  staticfiles:
    handler: static/staticfile.handler
    events:
      - http:
          path: /{url}
          method: get
  siebel-api:
    handler: api/siebel.handler
    timeout: 300
    events:
      - http:
          path: /api/siebel/import
          method: post

package:
  exclude:
    - .git/**
    - .deployment/**

plugins:
  - serverless-offline
  - '@cruglobal/serverless-merge-config'
