service: scale-of-belief-import
frameworkVersion: '3'
configValidationMode: error
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  stage: ${env:ENVIRONMENT}
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-888294ed
    subnetIds:
      - subnet-f2c2dfda # us-east-1a
      - subnet-1508db62 # us-east-1b
      - subnet-3fd94266 # us-east-1c
  stackTags:
    Name: ${env:PROJECT_NAME}-${self:custom.environmentMap.${env:ENVIRONMENT}}
    owner: apps@cru.org
    application: ${env:PROJECT_NAME}
    env: ${self:custom.environmentMap.${env:ENVIRONMENT}}
    managed_by: serverless-framework
    function: lambda
  memorySize: 256
  apiKeys:
    - ${opt:stage}-siebel-api-key
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:ListBucket
            - s3:GetObject
          Resource:
            - arn:aws:s3:::${env:CAMPAIGN_SNOWPLOW_S3_BUCKET}
            - arn:aws:s3:::${env:CAMPAIGN_SNOWPLOW_S3_BUCKET}/*
  layers:
    - arn:aws:lambda:us-east-1:072686360478:layer:node-16_14_2:1
  environment: ${file(env.js)}

package:
  individually: true
  patterns:
    - '!.serverless/**'
    - '!.webpack/**'
    - '!.git/**'
    - '!test/**'
    - '!**/*.test.js'
    - '!**/*.sql'
    - '!.deployment/**'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
    excludeFiles: '**/*.test.js'
    excludeRegex: \.ts|test|\.map
  environmentMap:
    production: prod
    staging: stage
    development: dev
    lab: lab

functions:
  api:
    handler: api/import.handler
    timeout: 300
    events:
      - http:
          path: /api/import
          method: ANY
  campaign:
    handler: campaign/import.handler
    timeout: 300
    memorySize: 1024
    events:
      - schedule: cron(5 6 * * ? *)
  staticfiles:
    handler: static/staticfile.handler
    events:
      - http:
          path: /{url}
          method: get
  siebel-api:
    handler: api/siebel.handler
    timeout: 30
    events:
      - http:
          path: /api/siebel/import
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Accept
          private: true
